plugin: aws_ec2
regions:
  - me-south-1
keyed_groups:
  - prefix: arch
    key: 'architecture'
  - prefix: tag
    key: 'tags'
  - prefix: aws_region
    key: placement.region
  - key: tags.Environment
    separator: ''
  - key: instance_type
    prefix: instance_type