---
- hosts: localhost
  tasks:
    - ec2_instance:
        key_name: test-ec2-creation-key
        instance_type: t3.micro
        image_id: ami-0f8d2a6080634ee69
        region: me-south-1
        #count: 1
        exact_count: 2
        filters:
          "tag:type": http
        vpc_subnet_id: subnet-4c04f425
        network:
          assign_public_ip: true
        security_groups: ["default"]
        tags: {type: http, Environment: QA}
        wait: yes
      register: ec2_output
    - debug: var=ec2_output