trigger:
- main

pool:
  vmImage: ubuntu-latest

stages: 
  - stage: Build
    jobs:
      - job: FirstJob
        steps: 
        - bash: ls -R $(Build.ArtifactStagingDirectory)
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: |
              **/*.yaml
              **/*.tf
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - bash: ls -R $(Build.ArtifactStagingDirectory)
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
