trigger:
- main

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'

pool:
  vmImage: $(imageName)

steps:
- script: echo Running image from $(imageName)
  displayName: 'Run a one-line script'
